const byId = (id) => document.getElementById(id);
const label = (value) => String(value).replaceAll('_', ' ');
async function getJSON(path) { const response = await fetch(path, { headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error(`${path} returned HTTP ${response.status}`); return response.json(); }
function renderSurfaces(surfaces) { const root = byId('surfaces'); root.replaceChildren(); for (const [name, state] of Object.entries(surfaces)) { const card = document.createElement('article'); card.className = 'card'; const heading = document.createElement('h3'); heading.textContent = label(name); const value = document.createElement('p'); value.textContent = label(state); card.append(heading, value); root.append(card); } }
function renderPlatformSystems(systems) { const root = byId('platform-systems'); root.replaceChildren(); systems.forEach((system) => { const card = document.createElement('article'); card.className = 'card'; const heading = document.createElement('h3'); heading.textContent = system.name; const value = document.createElement('p'); value.textContent = `${label(system.state)} · evidence: ${label(system.evidence)}`; card.append(heading, value); root.append(card); }); }
function renderCapabilities(capabilities) { const root = byId('capabilities'); root.replaceChildren(); capabilities.forEach((capability) => { const row = document.createElement('article'); row.className = 'capability'; const heading = document.createElement('strong'); heading.textContent = `${capability.id} — ${label(capability.state)}`; const detail = document.createElement('span'); detail.textContent = capability.detail; row.append(heading, detail); root.append(row); }); }
function renderOverview(overview) { byId('device-count').textContent = overview.deviceCount; byId('resource-count').textContent = overview.resourceCount; byId('policy-count').textContent = overview.policyCount; byId('policy-mode').textContent = label(overview.policyMode); byId('persistence').textContent = label(overview.persistence); byId('schema-version').textContent = overview.schemaVersion; byId('revision').textContent = overview.revision; byId('migration-count').textContent = overview.migrationCount; byId('integrity').textContent = label(overview.integrity); byId('last-persisted').textContent = overview.lastPersistedAt || 'Not persisted'; byId('authentication').textContent = label(overview.authentication); }
function renderAuthentication(authentication) { byId('identity-authority').textContent = label(authentication.authority); byId('identity-protocol').textContent = label(authentication.protocol); byId('identity-runtime').textContent = authentication.runtimeConfigured ? 'Configured — acceptance pending' : 'Not configured'; byId('identity-scope').textContent = authentication.requiredScope; byId('identity-accepted').textContent = authentication.productionAccepted ? 'Yes' : 'No'; byId('identity-detail').textContent = authentication.detail; }
async function refresh() { const error = byId('error'); error.hidden = true; try { const [status, overview, authentication, systems, capabilities] = await Promise.all([getJSON('/api/v1/status'), getJSON('/api/v1/overview'), getJSON('/api/v1/authentication'), getJSON('/api/v1/platform-systems'), getJSON('/api/v1/capabilities')]); byId('product').textContent = status.product; byId('version').textContent = status.version; byId('server-lifecycle').textContent = status.lifecycle; byId('lifecycle').textContent = status.lifecycle; renderOverview(overview); renderAuthentication(authentication); renderSurfaces(status.surfaces); renderPlatformSystems(systems); renderCapabilities(capabilities); } catch (err) { error.textContent = `Dashboard could not load live server state: ${err.message}`; error.hidden = false; byId('lifecycle').textContent = 'Unavailable'; } }
byId('refresh').addEventListener('click', refresh); refresh();
